### PR TITLE
Multi-Module: go mod tidy

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>

## Description
`go mod tidy`for each module

## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by edwarnicke** [comment]
Good idea!  Rebase and push?

**Comment by edwarnicke** [comment]
@nickolaev Did you mean your comment for a different PR?  This one appears to be a run of go tidy and not much else... or am I missing something?

**Comment by denis-tingajkin** [comment]
@edwarnicke  done

**Pull request merged**
