### PR TITLE
Limit dependencies download attempts

### PR DESCRIPTION
**Pull request by stepan-anokhin**
Signed-off-by: Stepan Anokhin <stepan.anokhin@gmail.com>

Prevent infinite loop of `go mod download` attempts

## Description
In case of invalid/inaccessible go dependencies sanity-check will lust forever.  This PR limits a number of attempts. 

## Motivation and Context
Prevent infinite loop of `go mod download` attempts

## How Has This Been Tested?
- [x] Covered by existing integration testing
- [ ] Added integration testing to cover
- [x] Tested locally
- [ ] Have not tested

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nickolaev** [comment]
We have this same piece of code in all our Dockerfiles.

**Comment by stepan-anokhin** [comment]
@nickolaev yep, done

**Comment by nickolaev** [comment]
@stepan-anokhin cna you please fix this:
https://github.com/networkservicemesh/networkservicemesh/blob/master/.circleci/config.yml#L23

to be:
```yaml
go get golang.org/x/lint/golint
```

**Comment by stepan-anokhin** [comment]
@nickolaev done. Now the PR does the following:

1. limits the amount of `go mod download` attempts
2. removes go pkg VCS cache. Now `go mod download` will re-fetch missing packages, so it should make build much more robust in cases like with `cloud.google.com/go`

**Comment by stepan-anokhin** [comment]
Now re-attempting to download dependencies actually resolves the problem:
```
go: cloud.google.com/go@v0.0.0-20160913182117-3b1ae45394a2: git -c protocol.version=0 fetch --unshallow -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/b0e27935eb83c1d7843713bafab507e95768b550f0552cb42d9f41e5fd9c8375: exit status 128:
	fatal: bad object a5913b3f7deecba45e98ff33cefbac4fd204ddd7
	error: remote did not send all necessary objects
go: error loading module requirements
Trying again, attempt 2
go: finding cloud.google.com/go v0.0.0-20160913182117-3b1ae45394a2
 ---> f7214847d4fe
```

**Pull request merged**
