### PR TITLE
NSM DNS simplification

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>

## Description
Coredns guys suggested using forward plugin with zones handling instead of fanout plugin to improve performance. 
This way looks good for us and it also some simplify NSM DNS specific part. We also can still use fanout plugin for conflict resolution.

## Motivation and Context
1. Removed nsm-coredns image from mono repo
2. Removed plugin fanout(moved to separate repo https://github.com/networkservicemesh/fanout)
3. Plugin fanout using only for resolving conflicts.

## How Has This Been Tested?

- [X] Covered by existing integration testing
- [X] Added integration testing to cover
- [X] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by denis-tingajkin** [comment]
TODO: improve docs

**Comment by denis-tingajkin** [comment]
Pr is not ready to merge yet, but be free to comment

**Comment by edwarnicke** [comment]
@denis-tingajkin This looks good to me, could you rebase?

**Comment by denis-tingajkin** [comment]
@edwarnicke done

**Pull request merged**
