### PR TITLE
CI multi cluster

### PR DESCRIPTION
**Pull request by nickolaev**
## Description
Deploy 2 clusters on Packet to parallelize the test execution.

## Motivation and Context
We can use a bit more power from Packet by parallelising the execution of the tests.
This PR migrates the CircleCI configuration to v2.1 which adds parametrization. This allows
for better-structured testing as well as easier splitting of the deployment phase to smaller steps.

NOTE: This one will potentially break local `make packet-*` commands.

## How Has This Been Tested?

- [X] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by edwarnicke** [comment]
This looks like you are still in progress (unless I'm misreading).  You are creating two clusters, and have revamped the testing to use cluster1... but I don't see cluster2 used.   Am I reading things right? :)

**Comment by edwarnicke** [comment]
Doh... you marked it WIP... I shouldn't code review before coffee :)

One other idea... perhaps we make the second cluster an IPv6 cluster?  Would give us some coverage on K8s configured for IPv6 :)

**Comment by nickolaev** [comment]
@edwarnicke I'll consider IPv6, makes sense.

Do you think a 3 node cluster is feasible too? It will allow us to enable 3 node scenarios. The first one that comes to mind (and I have tried it with kind already) is the VPN example. In it, we can run the client, firewall and VPN-GW on separate nodes. We don't have much of these today though.

**Comment by nickolaev** [comment]
@edwarnicke @fkautz this one is ready for review.

**Pull request merged**
