### PR TITLE
NSM init monitoring container

### PR DESCRIPTION
**Pull request by haiodo**
## Description

Initial implementation if NSM-Monitor:
* Monitor connections.
* Perform healing if both NSM and dataplane are restarted and respond with empty list of connections to client.

#1331 scenario N9.

## Motivation and Context

Client infrastructure should be recovered in any possible situation.

## How Has This Been Tested?

- [x] Covered by existing integration testing
- [x] Added integration testing to cover
- [x] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by haiodo** [comment]
@edwarnicke  @nickolaev this is initial part of healing improvements, 
it mostly works, but not fully covered by integration tests.

It is suited as base codebase for DNS changes to be integrated by @denis-tingajkin .

I will add more tests and improvements in next pull requests.

**Comment by haiodo** [comment]
Fully thing, Kubernetes Device plugin give same deviceId for every container in one pod, so we have same workspace mounted to any container.

**Comment by nickolaev** [comment]
@haiodo @denis-tingajkin is this one still valid after the merge of #1363? Shall we close it?

**Comment by haiodo** [comment]
Nope, It is not valid anymore. Closed.

**Pull request closed without merging**
