### PR TITLE
Use fixed version of k8s

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>

## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [X] Tested locally
- [ ] Have not tested

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nickolaev** [comment]
why not the latest in 1.14 release, v1.14.5.

**Comment by denis-tingajkin** [comment]
Let's wait tests finish

**Comment by haiodo** [comment]
@nickolaev @denis-tingajkin  I suppose since @nickolaev fixed CRDs we do not really need it now.

**Comment by denis-tingajkin** [comment]
TODO: use version 1.15.4

**Comment by edwarnicke** [comment]
Merging because the test failure should be fixed by #1643 which is failing because of what this fixes.

**Pull request merged**
