### PR TITLE
Field for arbirary k,v data in the message IPContext

### PR DESCRIPTION
**Pull request by uablrek**
## Description

Add in message IPContext;
```
map<string, string> extra_context = 11; /* a k,v map for transfering arbitrary information from an NSE to an NSC or dataplane */
```

## Motivation and Context

Often some extra data needs to be exchanged. This PR makes that possible without altering the protocol every time.

## How Has This Been Tested?
- [x] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by haiodo** [comment]
Hi @uablrek,

I personally think IPContext is not a good candidate for any custom information, better to have a additional context object with this information.

**Comment by uablrek** [comment]
@haiodo I have no opinion myself in this matter. I just created this PR whith this feature that I tought was agreed with @edwarnicke.

**Comment by edwarnicke** [comment]
@haiodo I think the information that @uablrek has in mind is in fact IPContext... just not of the sort we've envisioned so far.  I think this could be done either here (and in EthernetContext, and DNSContext, etc) or we could do it once at the ConnectionContext level.  I'm inclined to suggest additional_context as a name at the ConnectionContext level.  @uablrek thoughts?

**Comment by uablrek** [comment]
Sounds reasonable to have it in ConnectionContext since it is supposed to be general parameters. I will make the change.

**Comment by edwarnicke** [comment]
@uablrek Looks great... could you also push a PR to https://github.com/networkservicemesh/api

**Pull request merged**
