### PR TITLE
Go mod vendor

### PR DESCRIPTION
**Pull request by lobkovilya**
## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by edwarnicke** [comment]
Why are we looking at returning to vendoring? :)

**Comment by lobkovilya** [comment]
First of all it is not "returning" :) Because now it is kind of hybrid mode of `go mod` and `vendor`. Flow is almost the same with `go mod` - just use `go get ...`, dependency stored to `go.mod`, but right before commit you have to exec `go mod vendor`. 

Anyway I just experiment with that and obviously that decision requires discussion. But there are couple good points:
- we are not depend on some servers that hosts dependencies (there were situation when servers weren't available)
- build time on CI reduces from ~4,5 min to ~2 min

**Comment by nickolaev** [comment]
I have doubts here too. Let's see how this goes and we can decide.

**Comment by edwarnicke** [comment]
@lobkovilya Are we not hitting the docker layer cache for building in CI?

**Pull request closed without merging**
