### PR TITLE
Update azure eks cluster version

### PR DESCRIPTION
**Pull request by pringlewood**
Signed-off-by: Wayne <Wayne@flickswitch.co.za>

## Description
CI is failing because of unsupported AKS version, bump to 1.17.8

## How Has This Been Tested?

- [x] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by edwarnicke** [comment]
Many thanks!

**Comment by edwarnicke** [comment]
@pringlewood Do you think this is related to the issue in CI for https://github.com/networkservicemesh/networkservicemesh/pull/2190 ?

**Comment by pringlewood** [comment]
@edwarnicke yes it is, AKS only supports latest minor patch version - 2 as per docs. I guess this is going to keep on occurring as they roll updates.

**Comment by edwarnicke** [comment]
@pringlewood Yes... there appear to be some other minor complications on the upgrade that are being worked out by @haiodo

**Pull request closed without merging**
