### PR TITLE
Skip interdomain tests pending fixes.

### PR DESCRIPTION
**Pull request by edwarnicke**
## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by edwarnicke** [comment]
@nickolaev @fkautz @haiodo We are merging things that are failing on Interdomain tests pending fixes (being worked on).  Leaving them failing simply makes it confusing to do code review and for contributors.  I suggest we disable them pending fixes for interdomain.

**Comment by fkautz** [comment]
If they are adding noise and are not indicative of a failure from the given pr, let's disable them for now.

Can we reproduce this locally?

**Comment by edwarnicke** [comment]
@fkautz My understanding is that @artem-belov can reproduce... but still trying to figure out why its not working.

**Comment by denis-tingajkin** [comment]
seems to me we have similar PR, please take a look at https://github.com/networkservicemesh/networkservicemesh/pull/1706

**Comment by haiodo** [comment]
@edwarnicke I've merged PR from Artyom to disable Interdomain tests, tests fails only for AWS.

**Comment by haiodo** [comment]
Will close this PR if master will be green with no interdomain on AWS.

**Pull request closed without merging**
