### PR TITLE
fix: Admission-webhook is using the wrong container registry, org and tag for CoreDNS

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

## Motivation and Context
https://github.com/networkservicemesh/networkservicemesh/issues/2212

## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by LionelJouin** [comment]
Using this version, I am now able to change the registry and the repository but I am still not able to change the tag.

Also, I am able to set the registry and the repository only if I put them together in the environment variable `REPO` of the admission-webhook pod.

**Comment by denis-tingajkin** [comment]
@LionelJouin Note: we are using CoreDNS with the master version from a separate repo by default. So we cannot set for CoreDNS image some specific version. As a solution I see a variant to add some additional env for CoreDNS image but it looks not good for me. 
What are the problems you see with using a custom repo and master version?

**Comment by denis-tingajkin** [comment]
@LionelJouin Yes, and it looks correct for me because of CoreDNS container **is not part of this repository.**

**Comment by denis-tingajkin** [comment]
Here failing build because on CI we are using networkservicemeshci repository that has not CoreDNS image. So it looks like this direction is invalid.

**Pull request closed without merging**
