### PR TITLE
Rename Helm template for forwarding plane

### PR DESCRIPTION
**Pull request by rdimitrov**
Needed as the Helm forwarding plane template was named after the VPP
forwarding plane.

Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>

## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by edwarnicke** [comment]
@rdimitrov Question... how would you forsee this evolving forward when we get to multiple forwarding planes?

**Comment by nickolaev** [comment]
IMO, each forwarding plane has to live in its own repo, providing the helmcharts for its deployment. That will be even more true once we get to "cross-connect-as-a service" (CCaaS?) model. Effectively the NSM deplyment will literally be - NSMgr as a Daemon Set.

**Comment by edwarnicke** [comment]
> IMO, each forwarding plane has to live in its own repo, providing the helmcharts for its deployment. That will be even more true once we get to "cross-connect-as-a service" (CCaaS?) model. Effectively the NSM deplyment will literally be - NSMgr as a Daemon Set.

Understood.  I expect an intermediate stage though where we are migrating to the "cross-connect-as -a-service" model and exercising multiple forwarders out of the networkservicemesh/ repo... so I guess I should recast my question for that medium term.

Also... even with the forwarders in their own repos (a good idea) I expect we will want to publish nsm artifacts in a common helm repo... so will want non-conflicting chart names there.

**Comment by rdimitrov** [comment]
So far we're using this general helm template for both VPP and the kernel-forwarder and I guess it was left behind at some point during the refactorings, so that's the reason for renaming it. 

About the question, until there's no difference between each forwarding plane, I guess we can loop over the list of forwarders we want to deploy using again the same helm template. 

But in case there're differences in their helm charts, I haven't thought of anything neat so far.

**Comment by edwarnicke** [comment]
@rdimitrov Ah... I'd missed [that it was handling both forwarding planes with a variable to switch on](https://github.com/networkservicemesh/networkservicemesh/blob/master/deployments/helm/nsm/templates/vppagent-forwarder.tpl#L1).  Given that this makes a lot of sense to me :)

Lets see if we can get it past CI.  Also, could we get it on release-0.2. as well?

**Comment by rdimitrov** [comment]
Great 👍 I'll prepare the same PR for the release-0.2 branch. 

ps. Do you want me to force push or we can re-run the CI?

**Pull request merged**
