### PR TITLE
Liveness monitor server

### PR DESCRIPTION
**Pull request by artem-belov**
Signed-off-by: Artem Belov <artem.belov@xored.com>

## Description
Liveness monitor throws error in Error channel on losing connection 

## Motivation and Context
Required for Floating Intedomain (#1592) and plugins re-registration (#1665)

## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [x] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by edwarnicke** [comment]
Could you explain the purpose in adding this?

**Comment by artem-belov** [comment]
@edwarnicke 
For Floating interdomain we need to monitor nsmd from remote registry server to be sure that all registered NSEs are available for connection.
For #1665 we need to monitor plugin to start re-register process on plugins's restart

**Comment by edwarnicke** [comment]
@artem-belov OK... so you are trying to figure out if an NSE that has registered has gone away.  Liveliness probing across domains is not a scalable way to do that.  It also hits all kinds of problems when you have semi-isolated connectivity domains.

Instead of doing liveliness probes... we should think about properly expiring NSE registrations.

One way of doing so would be to add an 'ExpiresAt' field to [NetworkServiceEndpoint](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/api/registry/registry.proto#L31) in the registry.  We could then 

1.  Not select expired NSEs
2. Have something that reaps expired NSEs from the registry.

**Comment by alex-yust** [comment]
@edwarnicke the livemonitor is still a nice solution to monitor service liveness at least inside domain, since it takes only 1 line of code to get a liveness server on a grpc connection (please look at #1665) 
and few lines of code to monitor it.

**Pull request closed without merging**
