### PR TITLE
Use stats poller service for vpp-agent forwarder metrics

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

## Motivation and Context
https://github.com/networkservicemesh/networkservicemesh/issues/1512

## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nickolaev** [comment]
Should we mention this is vppagent related?

**Comment by denis-tingajkin** [comment]
@nickolaev thanks, title updated

**Comment by denis-tingajkin** [comment]
This PR is blocked. 
Reason: I faced with unexpected behavior. I've created an issue in ligato repo: https://github.com/ligato/vpp-agent/issues/1590

**Comment by denis-tingajkin** [comment]
The problem is solved on vpp-agent side. We need to wait new release.

**Pull request merged**
