### PR TITLE
Add Helm chart installation tests

### PR DESCRIPTION
**Pull request by lucperkins**
## Description

This PR adds CircleCI testing for the various NSM Helm charts using the [`ct`](https://github.com/helm/chart-testing) tool.

## Motivation and Context

These tests exist to ensure, at the CI level, that Helm charts are installable and properly formed.

## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [x] Added integration testing to cover
- [x] Tested locally
- [ ] Have not tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by edwarnicke** [comment]
@lucperkins This looks good!  Many thanks :)  Now just waiting on CI :)

**Comment by edwarnicke** [comment]
@lucperkins Looks like you have angered the shellcheck guys.  The good news is that the shellcheck guys tend to give clear errors, backed by a [secret decoder ring](https://github.com/koalaman/shellcheck/wiki/SC2086) :)

**Comment by lucperkins** [comment]
@edwarnicke Hehe, yeah I saw that 😄 Should just take a few runs here to get it right.

**Comment by edwarnicke** [comment]
@lucperkins Totally normal :)

**Comment by lucperkins** [comment]
@fkautz @edwarnicke The new Helm job is now working fine but CI is getting hung up on one of the GKE-related jobs. Is that a known issue and unrelated to this PR?

**Comment by nickolaev** [comment]
I'm ok with this, but maybe we need to point the `ct` to a cluster where it can actually install the helm charts. It seems it only does linting today.

**Comment by lucperkins** [comment]
@nickolaev This PR is just a start. Other checks can be added later.

**Pull request merged**
